name: Garnix CI

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  garnix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run Flake Checks
        run: nix flake check --print-build-logs

      - name: Format Check
        run: nix run nixpkgs#nixfmt -- --check .
